FROM node:alpine

LABEL maintainer="Caglar Yalcin <caglaryalcin.com>"

LABEL org.opencontainers.image.source = "https://github.com/caglaryalcin/caglaryalcin.com"

EXPOSE 8000

RUN \
  apk add --no-cache python3 make g++ && \
  apk add vips-dev fftw-dev --update-cache \
  --repository http://dl-3.alpinelinux.org/alpine/edge/community \
  --repository http://dl-3.alpinelinux.org/alpine/edge/main \
 && rm -fR /var/cache/apk/*

RUN apk add automake autoconf libtool nasm

RUN npm install -g gatsby-cli node-gyp

WORKDIR /app
COPY . .
RUN yarn install && yarn cache clean

CMD ["yarn", "develop", "-H", "0.0.0.0" ]
