name: Gatsby Docker Build & Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: clone repo
        uses: actions/checkout@v3

      - name: login with docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: docker image build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/caglaryalcin.com:latest .

      - name: docker image push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/caglaryalcin.com:latest

      - name: github login
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: ghcr image tag
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/caglaryalcin.com:latest ghcr.io/${{ github.repository_owner }}/caglaryalcin.com:latest

      - name: ghcr push
        run: docker push ghcr.io/${{ github.repository_owner }}/caglaryalcin.com:latest
